site_name:        StanJulia/CmdStan.jl
repo_url:         https://github.com/StanJulia/CmdStan.jl
site_description: Package to run cmdstan from Julia
site_author:      StanJulia

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md